[tools]
neovim          = "0.11.6"
eza             = "0.23.4"
fzf             = "0.68.0"
ripgrep         = "15.1.0"
yq              = "4.52.4"
zoxide          = "0.9.9"
starship        = "1.24.2"
bat             = "0.26.1"
fd              = "10.3.0"
terraform       = "1.14.6"
packer          = "1.15.0"
lazygit         = "0.59.0"
gdu             = "5.33.0"
bottom          = "0.12.3"
rust            = "1.93.1"
python          = "system"
pipx            = "1.8.0"
ansible         = "13.4.0"
"cargo:pokeget" = "1.6.7"
fastfetch        = "latest"
claude           = "latest"
